
  0%|                                                    | 0/10 [00:00<?, ?it/s]/home/yl3427/cylab/selfCorrectionAgent/src/agent.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_dataset.loc[idx, f"mem_{self.label}_reasoning"] = json_output['reasoning']
/home/yl3427/cylab/selfCorrectionAgent/src/agent.py:131: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_dataset.loc[idx, f"mem_{self.label}_ans_str"] = json_output['predictedStage']








100%|███████████████████████████████████████████| 10/10 [01:57<00:00, 11.71s/it]
  0%|                                                    | 0/20 [00:00<?, ?it/s]
  0%|                                                    | 0/20 [00:00<?, ?it/s]/home/yl3427/cylab/selfCorrectionAgent/src/agent.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_dataset.loc[idx, f"mem_{self.label}_reasoning"] = json_output['reasoning']
/home/yl3427/cylab/selfCorrectionAgent/src/agent.py:157: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_dataset.loc[idx, f"mem_{self.label}_ans_str"] = json_output['predictedStage']








 45%|███████████████████▊                        | 9/20 [00:30<00:35,  3.21s/it]Traceback (most recent call last):
  File "/home/yl3427/cylab/selfCorrectionAgent/src/test_memory.py", line 56, in <module>
    test_result = memory_agent.test(df_testing_samples)
  File "/home/yl3427/cylab/selfCorrectionAgent/src/agent.py", line 149, in test
    json_output = self.get_schema_followed_response(messages, self.schema_dict["testing_schema"], temperature)
  File "/home/yl3427/cylab/selfCorrectionAgent/src/agent.py", line 87, in get_schema_followed_response
    response = self.client.chat.completions.create(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/yl3427/cylab/selfCorrectionAgent/src/test_memory.py", line 56, in <module>
    test_result = memory_agent.test(df_testing_samples)
  File "/home/yl3427/cylab/selfCorrectionAgent/src/agent.py", line 149, in test
    json_output = self.get_schema_followed_response(messages, self.schema_dict["testing_schema"], temperature)
  File "/home/yl3427/cylab/selfCorrectionAgent/src/agent.py", line 87, in get_schema_followed_response
    response = self.client.chat.completions.create(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
KeyboardInterrupt