2024-06-11 00:41:59,344 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Configure stats pid to 2362618
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Loading settings from /home/yl3427/.config/wandb/settings
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Loading settings from /home/yl3427/cylab/selfCorrectionAgent/wandb/settings
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/test_memory.py', 'program_abspath': '/home/yl3427/cylab/selfCorrectionAgent/src/test_memory.py', 'program': '/home/yl3427/cylab/selfCorrectionAgent/src/test_memory.py'}
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:_log_setup():520] Logging user logs to /home/yl3427/cylab/selfCorrectionAgent/wandb/run-20240611_004159-545gsl9y/logs/debug.log
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:_log_setup():521] Logging internal logs to /home/yl3427/cylab/selfCorrectionAgent/wandb/run-20240611_004159-545gsl9y/logs/debug-internal.log
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:init():560] calling init triggers
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'class': 'ConditionalMemoryAgent', 'model': 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'label': 't', 'date': '06110041'}
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:init():610] starting backend
2024-06-11 00:41:59,345 INFO    MainThread:2362618 [wandb_init.py:init():614] setting up manager
2024-06-11 00:41:59,347 INFO    MainThread:2362618 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-11 00:41:59,349 INFO    MainThread:2362618 [wandb_init.py:init():622] backend started and connected
2024-06-11 00:41:59,353 INFO    MainThread:2362618 [wandb_init.py:init():711] updated telemetry
2024-06-11 00:41:59,373 INFO    MainThread:2362618 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-11 00:41:59,655 INFO    MainThread:2362618 [wandb_run.py:_on_init():2402] communicating current version
2024-06-11 00:41:59,719 INFO    MainThread:2362618 [wandb_run.py:_on_init():2411] got version response 
2024-06-11 00:41:59,719 INFO    MainThread:2362618 [wandb_init.py:init():795] starting run threads in backend
2024-06-11 00:42:03,595 WARNING MainThread:2362618 [wandb_init.py:init():1175] interrupted
Traceback (most recent call last):
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/yl3427/miniconda3/envs/selfCorrection/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-06-11 00:42:14,365 WARNING MsgRouterThr:2362618 [router.py:message_loop():77] message_loop has been closed
